export const crisesDummyData = [
  {
    title: "Flood in City Aaaaaaaaaaaaaaaaaaaaaaaaa",
    description:
      "Severe flooding affecting the lower areas of the city asdasdasddddddddddddddddddddddd",
    imageUrls: ["flood1.jpg", "flood2.jpg"],
    locations: ["Area A", "Area B"],
    severity: "HIGH",
    status: "ACTIVE",
    requiredHelp: "Need boats and volunteers for evacuation",
    approvedBy: 1, // assuming user with ID 1 exists
  },
  {
    title: "Earthquake in Region B",
    description: "Magnitude 6.5 earthquake causing severe damage",
    imageUrls: ["earthquake1.jpg", "earthquake2.jpg"],
    locations: ["Region B"],
    severity: "CRITICAL",
    status: "ACTIVE",
    requiredHelp: "Need medical assistance and engineers",
    approvedBy: 2, // assuming user with ID 2 exists
  },
  {
    title: "Wildfire in Forest C",
    description: "A large wildfire spreading rapidly across the forest",
    imageUrls: ["wildfire1.jpg", "wildfire2.jpg"],
    locations: ["Forest C", "Nearby villages"],
    severity: "CRITICAL",
    status: "PENDING",
    requiredHelp: "Firefighters and helicopters for water drops",
    approvedBy: 3,
  },
  {
    title: "Landslide in Mountain D",
    description: "Heavy rain triggered a landslide in the mountainous area",
    imageUrls: ["landslide1.jpg"],
    locations: ["Mountain D"],
    severity: "HIGH",
    status: "RESOLVED",
    requiredHelp: "Need heavy machinery to clear the debris",
    approvedBy: 4,
  },
  {
    title: "Tornado in Town E",
    description:
      "A tornado caused severe damage to buildings and infrastructure",
    imageUrls: ["tornado1.jpg", "tornado2.jpg"],
    locations: ["Town E"],
    severity: "MEDIUM",
    status: "ACTIVE",
    requiredHelp: "Construction workers and material to rebuild homes",
    approvedBy: 1,
  },
  {
    title: "Drought in Region F",
    description: "Prolonged drought affecting crops and livestock",
    imageUrls: ["drought1.jpg", "drought2.jpg"],
    locations: ["Region F"],
    severity: "LOW",
    status: "PENDING",
    requiredHelp: "Water and food supplies for affected areas",
    approvedBy: 2,
  },
  {
    title: "Hurricane in Coast G",
    description: "Hurricane causing flooding and wind damage to coastal areas",
    imageUrls: ["hurricane1.jpg", "hurricane2.jpg"],
    locations: ["Coast G", "Nearby islands"],
    severity: "CRITICAL",
    status: "ACTIVE",
    requiredHelp: "Rescue teams and food supplies for displaced people",
    approvedBy: 3,
  },
  {
    title: "Blizzard in City H",
    description: "Heavy snowstorm causing road closures and power outages",
    imageUrls: ["blizzard1.jpg"],
    locations: ["City H", "Surrounding towns"],
    severity: "MEDIUM",
    status: "RESOLVED",
    requiredHelp: "Snowplows and repair teams for power restoration",
    approvedBy: 4,
  },
  {
    title: "Heatwave in Region I",
    description: "Extreme temperatures causing health risks and wildfires",
    imageUrls: ["heatwave1.jpg", "heatwave2.jpg"],
    locations: ["Region I"],
    severity: "HIGH",
    status: "PENDING",
    requiredHelp: "Cooling centers and medical teams for heatstroke",
    approvedBy: 1,
  },
  {
    title: "Flood in Valley J",
    description: "Heavy rain causing river overflow and floods in nearby areas",
    imageUrls: ["flood_valley1.jpg", "flood_valley2.jpg"],
    locations: ["Valley J", "Village X"],
    severity: "HIGH",
    status: "ACTIVE",
    requiredHelp: "Evacuation teams and shelters for displaced families",
    approvedBy: 2,
  },
];
